"""dataengr URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import RedirectView

from routers import HybridRouter
from api.views import *

# Global DRF Router that routes views from all apps in project
router = HybridRouter()

# app views and viewsets
router.register(r'news_item', NewsItemSet, r"news_item")


urlpatterns = [
    # default django admin interface
    #url(r'^admin/', include(admin.site.urls)),

    # root view of REST api, generated by Django REST Framework's router
    url(r'^api/', include(router.urls, namespace='api')),

    # auto redirect to API view
    url(r'^$', RedirectView.as_view(url='api', permanent=False)),
]
