"""dataengr URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""

from django.conf.urls import include, url
from django.views.generic import RedirectView

from routers import HybridRouter
from rest_framework import routers
from api import views

# Global DRF Router that routes views from all apps in project
router = routers.DefaultRouter()

router.register('news_item', views.NewsItemSet, 'news_item')
router.register('crawl', views.ScrapyCrawlSet, 'crawl' )


urlpatterns = [
    # default django admin interface
    #url(r'^admin/', include(admin.site.urls)),

    # root view of REST api, generated by Django REST Framework's router
    url(r'^api/', include(router.urls)),

    # auto redirect to API view
    url(r'^$', RedirectView.as_view(url='api', permanent=False)),
]
